spring.application.name=eventos
spring.datasource.url=jdbc:postgresql://localhost:5432/neki
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.web.resources.static-locations=file:src/main/resources/images/
auth-jwt-secret=Kjd84Kd03jLq9GpT7Wy4eFzB6NmX8Vj3
auth-jwt-expiration-miliseg=21600000
